[package]
name = "clearstreet"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.15", features = ["rustls-tls", "json"]}
tokio = { version = "1.44.2", features = ["full", "sync"]}
tracing = "0.1.41"
serde = { version = "1.0.219", features = ["derive", "serde_derive"] }
serde_json = "1.0.140"

[dev-dependencies]
mockito = "1.7.0"
